create admin_word pages
YutakaYamasaki/E-Learning2 pull request #2
Opened 2018-09-05 08:07 UTC by YutakaYamasaki

2018-09-05 09:35 UTC, YutakaYamasaki commented
Sorry . 
I was unable to unify the indentation of words_controller so I committed it again.

2018-09-06 01:33 UTC, inahsanjuan requested changes
- There is no link to go to the `words#index`

2018-09-06 01:33 UTC, inahsanjuan commented on app/views/admin/categories/_category.html.erb
> +        <td><%= link_to "Add Word", new_admin_category_word_path(category) %></td>
@YutakaYamasaki Try add a classes to your linkts to make it more like a button, something like:
`btn btn-primary btn-sm`

2018-09-06 01:33 UTC, inahsanjuan commented on app/views/admin/categories/_category.html.erb
>      <tr>
You can format your table like this:
![image](https://user-images.githubusercontent.com/20507565/45129335-c2312e00-b1b5-11e8-84a9-7592e657ba89.png)

2018-09-06 01:33 UTC, inahsanjuan commented on app/views/admin/words/_form.html.erb
> +                <%= f.submit "Create new word", class: "btn btn-primary form-control" %>
@YutakaYamasaki Fix indentation in this area.

2018-09-06 01:33 UTC, inahsanjuan commented on app/controllers/admin/words_controller.rb
> +      flash[:succees] = "Create Word."
@YutakaYamasaki Change `succees` to `success`.

2018-09-06 01:33 UTC, inahsanjuan commented on app/views/admin/words/_word.html.erb
> +        <td><%= link_to "delete", admin_category_word_path(@categories, word), method: "delete" %></td>
@YutakaYamasaki Try to change format of display, something like this: 
![image](https://user-images.githubusercontent.com/20507565/45129608-551e9800-b1b7-11e8-92c9-94212dd4f24d.png)

2018-09-06 01:33 UTC, inahsanjuan commented on app/views/admin/words/edit.html.erb
> +        <div class="text-center"><%= yield(:title) %></div>
@YutakaYamasaki Update this element to `<h1>`

2018-09-07 02:19 UTC, merged