Create lesson
YutakaYamasaki/E-Learning2 pull request #3
Opened 2018-09-08 16:17 UTC by YutakaYamasaki

2018-09-13 04:35 UTC, inahsanjuan requested changes

2018-09-13 04:35 UTC, inahsanjuan commented on db/migrate/20180904094955_create_words.rb
> +      t.string :category_id, foreign_key: true
@YutakaYamasaki `category_id` should be `integer`.
Or you can use `t.references :category`

2018-09-13 04:35 UTC, inahsanjuan commented on db/migrate/20180904100034_create_word_answers.rb
> +      t.string :word_id,foreign_key: true
@YutakaYamasaki `t.references :word`

2018-09-13 04:35 UTC, inahsanjuan commented on db/migrate/20180905130120_create_lessons.rb
> +      t.string :category_id, foreign_key: true
@YutakaYamasaki Use `references` here

2018-09-13 04:35 UTC, inahsanjuan commented on db/migrate/20180906182028_create_lesson_words.rb
> +      t.integer :word_answer_id, foreign_key: true
@YutakaYamasaki Use `references` here

2018-09-13 04:35 UTC, inahsanjuan commented on app/controllers/lessons_controller.rb
> +		@user = current_user
@YutakaYamasaki I want to know why you assigned `current_user` to `@user`, when you can access `current_user` in your views.

2018-09-15 09:02 UTC, YutakaYamasaki commented on app/controllers/lessons_controller.rb
> +		@user = current_user
I was going to understand by making @user = current_user.
However, I understood it so I will fix it.

2018-09-18 01:19 UTC, inahsanjuan approved these changes

2018-09-18 01:19 UTC, merged